#此处配置所有服务公共配置
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
    driver-class-name: com.mysql.jdbc.Driver
    # url: jdbc:mysql://127.0.0.1:3306/youxuandb?autoReconnect=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    # username: root
    # password: 123456
    type: com.zaxxer.hikari.HikariDataSource

  rabbitmq:
    addresses: 192.0.0.1,192.0.0.1
    port: 5672
    username:
    password:

#logging:
#  config: classpath:logback.xml

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  # typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: INPUT
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
      #刷新mapper 调试神器
      refresh: false
      #原生配置
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false

management:
  server:
    port: 10000
    address: 127.0.0.1
  endpoints:
    web:
      #base-path: /mgmt
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
  info:
    git:
      mode: simple