# 此处配置该服务自己的配置
spring:
  redis:
    database: 0
    timeout: 200

  datasource:
    hikari:
      catalog: youxuan-goods-service
    url: jdbc:mysql://127.0.0.1:3306/youxuan-goods-service?autoReconnect=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456