# 此处配置该服务自己的配置
spring:
  redis:
    database: 0
    timeout: 200

  datasource:
    hikari:
      catalog: youxuan-search-service

es:
  cluster-name: es-application
  host: 192.168.10.11
  port: 9300
  index: youxuan
  type: item